using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace DynamicDataGridChange
{
    public partial class MainWindow : Window
    {
        private int _maxPins;

        public ObservableCollection<RowData> Rows { get; set; }
            = new ObservableCollection<RowData>();

        public MainWindow()
        {
            InitializeComponent();

            DataContext = this;

            CalculateMaxPins();
            GenerateColumns();
            LoadData("X"); // default
        }

        private void CalculateMaxPins()
        {
            _maxPins = DataProvider.Data.Values.Max(list => list.Count);
        }

        private void GenerateColumns()
        {
            dataGrid.Columns.Clear();

            // ImageId column
            dataGrid.Columns.Add(new DataGridTextColumn
            {
                Header = "ImageId",
                Binding = new Binding("ImageId")
            });

            // Dynamic Pin columns
            for (int i = 0; i < _maxPins; i++)
            {
                dataGrid.Columns.Add(new DataGridTextColumn
                {
                    Header = $"Pin{i + 1}",
                    Binding = new Binding($"Values[{i}]"),
                    Width = new DataGridLength(1, DataGridLengthUnitType.Star)
                });
            }
        }

        private List<RowData> BuildRows(string axis)
        {
            var rows = new List<RowData>();

            foreach (var image in DataProvider.Data.OrderBy(x => x.Key))
            {
                var row = new RowData
                {
                    ImageId = image.Key
                };

                var pins = image.Value;

                for (int i = 0; i < _maxPins; i++)
                {
                    if (i < pins.Count)
                    {
                        var pin = pins[i];

                        int value;

                        switch (axis)
                        {
                            case "X":
                                value = pin.XAxis;
                                break;
                            case "Y":
                                value = pin.YAxis;
                                break;
                            case "Z":
                                value = pin.ZAxis ?? 0;
                                break;
                            default:
                                value = 0;
                                break;
                        }

                        row.Values.Add(value);
                    }
                    else
                    {
                        row.Values.Add(0); // missing pin
                    }
                }

                rows.Add(row);
            }

            return rows;
        }

        private void LoadData(string axis)
        {
            Rows.Clear();

            var result = BuildRows(axis);

            foreach (var row in result)
                Rows.Add(row);
        }

        private void ButtonXClick(object sender, RoutedEventArgs e)
        {
            LoadData("X");
        }

        private void ButtonYClick(object sender, RoutedEventArgs e)
        {
            LoadData("Y");
        }

        private void ButtonZClick(object sender, RoutedEventArgs e)
        {
            LoadData("Z");
        }

        private void dataGrid_AutoGeneratedColumns(object sender, System.EventArgs e)
        {

        }
    }
}